### ISSUE TITLE
How to add more themes in https://bschwarz.github.io/puml-themes/gallery.html

### ISSUE THREAD

**Issue by kkweon** [bschwarz/puml-themes#18]
This is super helpful but I'm hoping to add more themes to the gallery.

![image](https://user-images.githubusercontent.com/2981167/136587491-f30950d9-d912-49d7-a5e3-f15cf4fc77f7.png)

(1) How to add more themes
(2) Can it be done programmatically? meaning all generated just from theme list (a list of strings).

**Comment by arnaudroques** [comment]
One way to add themes to the gallery is to push new themes to https://github.com/plantuml/plantuml/tree/master/themes
Themes pushed there will be integrated in next official PlantUML release.

**Comment by kkweon** [comment]
Hmm, what I mean is more like 

you see plain theme is available in https://github.com/plantuml/plantuml/blob/master/themes/puml-theme-plain.puml

but it's not shown on the gallery (https://bschwarz.github.io/puml-themes/gallery.html).

**Comment by kkweon** [comment]
Ideally, I'm hoping that all available themes are shown on the gallery.

**Comment by bschwarz** [comment]
The themes that are on the official plantuml repo consist of themes from my repo, as well as themes from other repos. The puml-theme-plain was authored by Matthew Leather. Although it looks like it was derived from one of my themes, it is not part of my repo, hence it is not in the gallery. 

We could do one of two things:

1. I can keep a copy of the themes in my repo as well, and generate the gallery
2. create a gallery on the plantuml.com website that shows all the themes

Both would create some initial work to accomplish this.

**Comment by kkweon** [comment]
Instead of hard copying themes, 

can this repo just fetch dynamically from plantuml before generating static sites and ideally become a theme gallery for all rather than theme gallery for those authored by you only?


Step 1. Get all themes from plantuml themes

@startuml
help themes
@enduml

Step 2. Generate static images and pages by replacing the theme line from pre defined templates.

Say prepare a basic puml without theme. 
And insert theme and generate static sites.

**Comment by bschwarz** [comment]
No, I don't want to do that. It would be a misrepresentation, since this repo is concerned with the themes that are in this repo. People may get confused to see themes in the gallery that are not in the repo. 

I think the best option would be for plantuml to host the gallery, if that is desired. I can provide the template/scripts that I have if that will help.

**Comment by kkweon** [comment]
Gotcha. Makes sense.
Where do i file a feature request for PlantUML to host it? 

And feel free to close this one

**Comment by bschwarz** [comment]
You will want to open it against the [plantuml official repo](https://github.com/plantuml/plantuml/issues). I believe you can create a feature there. And then if they need my help at all, I can help out.

**Comment by kkweon** [comment]
Thanks.
