### ISSUE TITLE
Don't support gantt?

### ISSUE THREAD

**Issue by billnote** [bschwarz/puml-themes#8]
Source puml:
```
@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/cerulean/puml-theme-cerulean.puml

[Prototype design] lasts 15 days
[Test prototype] lasts 10 days

Project starts 2020-07-01
[Prototype design] ends 2020-07-15
[Test prototype] ends 2020-07-25
@enduml
```

Output:
Some diagram description contains errors
[Prototype design] lasts 15 days
Syntax Error?

**Comment by bschwarz** [comment]
From what I can tell, there are no skinparams for gantt, so there's no way to style them specifically right now. If you know how, please let me know.

Do you get an error when you run you puml example? It works for me:

http://www.plantuml.com/plantuml/png/ROzFQiSW48Ntdi8Um6W2eT1LZj15Tw4BeqDCyOyu8o4zVGrjsX9-Ix_tlOSp8Ub2DNZsj4NZgmNkY3A-I5dqtgqRkRfKX69I98ZKcHJaWiRjkdpAt8g270H06JGI5FdpCb2g1nt_AU9YtSaOcrzBeaH71cu1jpM-SzysaFSZj_f0Dhy14i-NzHkhxvYr_WSOukS9ZGzgK48z2zK_cePe_vH-l8_VX65aKmFjdry0

Might depend on what version of plantuml you are using

**Comment by billnote** [comment]
Yes, I get an error when I run the puml example, My PlantUML version is 1.2020.17. I aslo don't know the way to style gantt.   
Thank you for your reply.

**Comment by bschwarz** [comment]
Are you able to download a newer version of plantuml? I just tried 1.2020.21 and it does not generate an error. It still does not style the gantt chart, but I don't think that's possible anyways.

**Comment by billnote** [comment]
the newer version plantuml (1.2020.21 )  is work.  Maybe only style files can be used to style the gantt chart.

**Comment by bschwarz** [comment]
I will close this issue for now. I will investigate style files for gantt charts. I think styles are still in beta though.
