### ISSUE TITLE
Many theme puml files named incorrectly

### ISSUE THREAD

**Issue by 27escape** [bschwarz/puml-themes#9]
many themes have been based upon sandstone and because of this they have not renamed the theme file from puml-theme-sandstone.puml to be something based on their theme name

For example, I get the error "The file !include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/solar/puml-theme-solar.puml does not exist"

Affected themes are united, minty, spacelab

**Comment by bschwarz** [comment]
Hi, 

thanks for the report. I have updated so that the filenames are correct now.

Also, there still won't be a solar file, because I haven't done that theme yet.

Thanks again,
Brett

**Comment by bschwarz** [comment]
closing
